### ISSUE TITLE
Flink on Amazon ECS crashes in "WikiEdit" example

### ISSUE THREAD

**Issue by maiconbaumx** [docker-flink/examples#9]
Hi!
I'm trying to create a Flink cluster on Amazon ECS with jobmanager and taskmanager in different task definitions. If I try to submit other examples available in Flink's website, seems work. However, the "WikiEdit" example that I'm sending the result to my kafka cluster, crashes in 90~110 seconds. If I try to deploy the same structure local (via Docker-Compose) this works like a charm. Any idea? :(

Logs:

> 2018-06-20 13:39:00,001 INFO  org.apache.flink.runtime.taskmanager.Task                     - Attempting to fail task externally Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed (1/1) (5d360677897b1276468e0a4727c6ba1f).
> 2018-06-20 13:39:00,002 INFO  org.apache.flink.runtime.taskmanager.Task                     - Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed (1/1) (5d360677897b1276468e0a4727c6ba1f) switched from RUNNING to FAILED.
> TimerException{org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator}
> 	at org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$TriggerTask.run(SystemProcessingTimeService.java:284)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:577)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:535)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:515)
> 	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:679)
> 	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:657)
> 	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
> 	at org.apache.flink.streaming.api.functions.windowing.PassThroughWindowFunction.apply(PassThroughWindowFunction.java:36)
> 	at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalSingleValueWindowFunction.process(InternalSingleValueWindowFunction.java:46)
> 	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindowContents(WindowOperator.java:550)
> 	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.onProcessingTime(WindowOperator.java:505)
> 	at org.apache.flink.streaming.api.operators.HeapInternalTimerService.onProcessingTime(HeapInternalTimerService.java:266)
> 	at org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$TriggerTask.run(SystemProcessingTimeService.java:281)
> 	... 7 more
> Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:577)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:535)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:515)
> 	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:679)
> 	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:657)
> 	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:560)
> 	... 18 more
> Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 67 ms.
> 2018-06-20 13:39:00,014 INFO  org.apache.flink.runtime.taskmanager.Task                     - Triggering cancellation of task code Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed (1/1) (5d360677897b1276468e0a4727c6ba1f).
> 2018-06-20 13:39:00,033 ERROR org.apache.flink.streaming.runtime.tasks.StreamTask           - Error during disposal of stream operator.
> org.apache.kafka.common.KafkaException: java.lang.InterruptedException
> 	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:424)
> 	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducerBase.close(FlinkKafkaProducerBase.java:319)
> 	at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
> 	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:473)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:374)
> 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:703)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.InterruptedException
> 	at java.lang.Object.wait(Native Method)
> 	at java.lang.Thread.join(Thread.java:1252)
> 	at java.lang.Thread.join(Thread.java:1326)
> 	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:422)
> 	... 7 more
> 2018-06-20 13:39:00,037 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed (1/1) (5d360677897b1276468e0a4727c6ba1f).
> 2018-06-20 13:39:00,082 INFO  org.apache.flink.runtime.taskmanager.Task                     - Ensuring all FileSystem streams are closed for task Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed (1/1) (5d360677897b1276468e0a4727c6ba1f) [FAILED]
> 2018-06-20 13:39:00,083 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Un-registering task and sending final execution state FAILED to JobManager for task Window(TumblingProcessingTimeWindows(30000), ProcessingTimeTrigger, FoldFunction$2, PassThroughWindowFunction) -> Map -> Sink: Unnamed 5d360677897b1276468e0a4727c6ba1f.
> 2018-06-20 13:39:00,105 INFO  org.apache.flink.runtime.taskmanager.Task                     - Attempting to cancel task Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a).
> 2018-06-20 13:39:00,105 INFO  org.apache.flink.runtime.taskmanager.Task                     - Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a) switched from RUNNING to CANCELING.
> 2018-06-20 13:39:00,106 INFO  org.apache.flink.runtime.taskmanager.Task                     - Triggering cancellation of task code Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a).
> 2018-06-20 13:39:00,110 INFO  org.apache.flink.runtime.taskmanager.Task                     - Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a) switched from CANCELING to CANCELED.
> 2018-06-20 13:39:00,110 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a).
> 2018-06-20 13:39:00,114 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Discarding the results produced by task execution 5d360677897b1276468e0a4727c6ba1f.
> 2018-06-20 13:39:00,117 INFO  org.apache.flink.runtime.taskmanager.Task                     - Ensuring all FileSystem streams are closed for task Source: Custom Source (1/1) (b7ab2070ada6626b3a1ab3f749a58d2a) [CANCELED]
> 2018-06-20 13:39:00,117 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Un-registering task and sending final execution state CANCELED to JobManager for task Source: Custom Source b7ab2070ada6626b3a1ab3f749a58d2a.
> 2018-06-20 13:39:00,142 INFO  org.apache.flink.runtime.taskexecutor.slot.TaskSlotTable      - Free slot TaskSlot(index:0, state:ACTIVE, resource profile: ResourceProfile{cpuCores=1.0, heapMemoryInMB=42, directMemoryInMB=0, nativeMemoryInMB=0, networkMemoryInMB=0}, allocationId: a05f140ecc711d103e6f5059ff3a2d2a, jobId: a6be4c4207ddc3bbc4172f60cbc7512a).
> 2018-06-20 13:39:00,143 INFO  org.apache.flink.runtime.taskexecutor.JobLeaderService        - Remove job a6be4c4207ddc3bbc4172f60cbc7512a from job leader monitoring.
> 2018-06-20 13:39:00,143 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Close JobManager connection for job a6be4c4207ddc3bbc4172f60cbc7512a.
> 2018-06-20 13:39:00,148 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Close JobManager connection for job a6be4c4207ddc3bbc4172f60cbc7512a.
> 2018-06-20 13:39:00,148 INFO  org.apache.flink.runtime.taskexecutor.JobLeaderService        - Cannot reconnect to job a6be4c4207ddc3bbc4172f60cbc7512a because it is not registered.

**Comment by maiconbaumx** [comment]
Sorry, my fault! I was trying to use a connector for Kafka 0.8 on my Kafka cluster 0.11. ;P
Closing!
